# Generated by Django 5.2.3 on 2025-06-20 02:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0005_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prescripcion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Prescripción')),
                ('esfera_od', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esfera OD')),
                ('cilindro_od', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro OD')),
                ('eje_od', models.IntegerField(blank=True, null=True, verbose_name='Eje OD')),
                ('adicion_od', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Adición OD')),
                ('prisma_od', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prisma OD')),
                ('base_od', models.CharField(blank=True, max_length=50, null=True, verbose_name='Base OD')),
                ('esfera_oi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esfera OI')),
                ('cilindro_oi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro OI')),
                ('eje_oi', models.IntegerField(blank=True, null=True, verbose_name='Eje OI')),
                ('adicion_oi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Adición OI')),
                ('prisma_oi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prisma OI')),
                ('base_oi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Base OI')),
                ('dnp_od', models.PositiveIntegerField(blank=True, null=True, verbose_name='DNP OD (mm)')),
                ('dnp_oi', models.PositiveIntegerField(blank=True, null=True, verbose_name='DNP OI (mm)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'ordering': ['-fecha_prescripcion', 'cliente__apellido_paterno'],
            },
        ),
    ]
