# Generated by Django 5.2.3 on 2025-06-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
