# Generated by Django 5.2.3 on 2025-06-11 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Principal')),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Opcional')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
    ]
