# Generated by Django 5.2.3 on 2025-06-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
    ]
