# Generated by Django 5.2.3 on 2025-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_direccion_cliente_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Adicional'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Principal'),
        ),
    ]
