# Generated by Django 5.2.3 on 2025-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_telefono2_alter_cliente_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono Principal'),
            preserve_default=False,
        ),
    ]
